// test data
import { LectureLabels } from './lecture-labels.js';

export const videos = [
    {
        title: "Linear Algebra Basics",
        description: "An introduction to vectors and matrices.",
        duration: "12:34",
        link: "https://www.youtube.com/watch?v=gC3qXcGPkR4&list=PLg1DqfAVb6DRcm0eicMuIKQLVA6sTr5KG",
        type: LectureLabels.LinearAlgebra,
    },
    {
        title: "Linear Algebra Basics",
        description: "An introduction to vectors and matrices.",
        duration: "12:34",
        link: "https://www.youtube.com/watch?v=gC3qXcGPkR4&list=PLg1DqfAVb6DRcm0eicMuIKQLVA6sTr5KG",
        type: LectureLabels.LinearAlgebra,
    },
    {
        title: "Linear Algebra Basics",
        description: "An introduction to vectors and matrices.",
        duration: "12:34",
        link: "https://www.youtube.com/watch?v=gC3qXcGPkR4&list=PLg1DqfAVb6DRcm0eicMuIKQLVA6sTr5KG",
        type: LectureLabels.LinearAlgebra,
    },
    {
        title: "Linear Algebra Basics",
        description: "An introduction to vectors and matrices.",
        duration: "12:34",
        link: "https://www.youtube.com/watch?v=gC3qXcGPkR4&list=PLg1DqfAVb6DRcm0eicMuIKQLVA6sTr5KG",
        type: LectureLabels.LinearAlgebra,
    },
    {
        title: "Linear Algebra Basics",
        description: "An introduction to vectors and matrices.",
        duration: "12:34",
        link: "https://www.youtube.com/watch?v=gC3qXcGPkR4&list=PLg1DqfAVb6DRcm0eicMuIKQLVA6sTr5KG",
        type: LectureLabels.LinearAlgebra,
    },
    {
        title: "Linear Algebra Basics",
        description: "An introduction to vectors and matrices.",
        duration: "12:34",
        link: "https://www.youtube.com/watch?v=gC3qXcGPkR4&list=PLg1DqfAVb6DRcm0eicMuIKQLVA6sTr5KG",
        type: LectureLabels.LinearAlgebra,
    },
    {
        title: "Linear Algebra Basics",
        description: "An introduction to vectors and matrices.",
        duration: "12:34",
        link: "https://www.youtube.com/watch?v=gC3qXcGPkR4&list=PLg1DqfAVb6DRcm0eicMuIKQLVA6sTr5KG",
        type: LectureLabels.LinearAlgebra,
    },
    {
        title: "Linear Algebra Basics",
        description: "An introduction to vectors and matrices.",
        duration: "12:34",
        link: "https://www.youtube.com/watch?v=gC3qXcGPkR4&list=PLg1DqfAVb6DRcm0eicMuIKQLVA6sTr5KG",
        type: LectureLabels.LinearAlgebra,
    },
    {
        title: "Linear Algebra Basics",
        description: "An introduction to vectors and matrices.",
        duration: "12:34",
        link: "https://www.youtube.com/watch?v=gC3qXcGPkR4&list=PLg1DqfAVb6DRcm0eicMuIKQLVA6sTr5KG",
        type: LectureLabels.LinearAlgebra,
    },
    {
        title: "Linear Algebra Basics",
        description: "An introduction to vectors and matrices.",
        duration: "12:34",
        link: "https://www.youtube.com/watch?v=gC3qXcGPkR4&list=PLg1DqfAVb6DRcm0eicMuIKQLVA6sTr5KG",
        type: LectureLabels.LinearAlgebra,
    },
    {
        title: "Linear Algebra Basics",
        description: "An introduction to vectors and matrices.",
        duration: "12:34",
        link: "https://www.youtube.com/watch?v=gC3qXcGPkR4&list=PLg1DqfAVb6DRcm0eicMuIKQLVA6sTr5KG",
        type: LectureLabels.LinearAlgebra,
    },
    {
        title: "Linear Algebra Basics",
        description: "An introduction to vectors and matrices.",
        duration: "12:34",
        link: "https://www.youtube.com/watch?v=gC3qXcGPkR4&list=PLg1DqfAVb6DRcm0eicMuIKQLVA6sTr5KG",
        type: LectureLabels.LinearAlgebra,
    },
    {
        title: "Advanced Linear Algebra",
        description: "Explore eigenvalues and eigenvectors.",
        duration: "20:45",
        link: "https://www.youtube.com/watch?v=gC3qXcGPkR4&list=PLg1DqfAVb6DRcm0eicMuIKQLVA6sTr5KG",
        type: LectureLabels.LinearAlgebra,
    },
    {
        title: "Math Analysis I",
        description: "Limits, derivatives, and integrals.",
        duration: "15:10",
        link: "https://www.youtube.com/watch?v=gC3qXcGPkR4&list=PLg1DqfAVb6DRcm0eicMuIKQLVA6sTr5KG",
        type: LectureLabels.MathAnalysis,
    },
    {
        title: "Probability Basics",
        description: "Introduction to probability theory.",
        duration: "18:50",
        link: "https://www.youtube.com/watch?v=gC3qXcGPkR4&list=PLg1DqfAVb6DRcm0eicMuIKQLVA6sTr5KG",
        type: LectureLabels.Probability,
    },
    {
        title: "Python for Beginners",
        description: "Learn Python from scratch.",
        duration: "25:00",
        link: "https://www.youtube.com/watch?v=gC3qXcGPkR4&list=PLg1DqfAVb6DRcm0eicMuIKQLVA6sTr5KG",
        type: LectureLabels.Python,
    },
    {
        title: "Machine Learning Overview",
        description: "Supervised and unsupervised learning concepts.",
        duration: "30:20",
        link: "https://www.youtube.com/watch?v=gC3qXcGPkR4&list=PLg1DqfAVb6DRcm0eicMuIKQLVA6sTr5KG",
        type: LectureLabels.MachineLearning,
    },

];
